import { PERFORMANCE_RECORDS } from "@/data/performance";
import { PLATFORM_BY_ID } from "@/data/platforms";
import { aggregateMetric } from "@/lib/analytics/comparisons";
import { calculatePercentageChange } from "@/lib/analytics/calculations";
import {
  filterPerformanceRecords,
  type DashboardRecordFilters,
} from "@/lib/dashboard/filter-records";
import type { DateRange, MetricId, PlatformId } from "@/types/analytics";

const SUMMARY_METRICS: MetricId[] = [
  "revenue",
  "orders",
  "roas",
  "ad_spend",
  "conversion_rate",
];

export interface ReportContentInput {
  title: string;
  periodLabel?: string;
  platformId?: PlatformId | "all";
  dateRange?: DateRange;
  comparisonRange?: DateRange;
  brandId?: string | null;
  productId?: string | null;
}

export function buildReportDocumentText(input: ReportContentInput): string {
  const filters: DashboardRecordFilters = {
    platformId: input.platformId ?? "all",
    brandId: input.brandId,
    productId: input.productId,
    dateRange: input.dateRange,
  };
  const current = filterPerformanceRecords(PERFORMANCE_RECORDS, filters);
  const comparisonFilters: DashboardRecordFilters = {
    ...filters,
    dateRange: input.comparisonRange,
  };
  const previous = input.comparisonRange
    ? filterPerformanceRecords(PERFORMANCE_RECORDS, comparisonFilters)
    : [];

  const platformLabel =
    input.platformId && input.platformId !== "all"
      ? PLATFORM_BY_ID[input.platformId]?.name ?? input.platformId
      : "All platforms";

  const lines: string[] = [
    input.title,
    "",
    `Generated by Ask Aria · Commerce Intelligence`,
    `Period: ${input.periodLabel ?? "Selected range"}`,
    `Scope: ${platformLabel}`,
    "",
    "Summary metrics",
    "────────────────",
  ];

  for (const metricId of SUMMARY_METRICS) {
    const currentVal = aggregateMetric(current, metricId);
    const prevVal = previous.length
      ? aggregateMetric(previous, metricId)
      : null;
    let change = "";
    if (prevVal !== null && prevVal !== 0) {
      const pct = calculatePercentageChange(prevVal, currentVal);
      change = ` (${pct >= 0 ? "+" : ""}${pct.toFixed(1)}% vs prior period)`;
    }
    lines.push(
      `${metricId.replace(/_/g, " ")}: ${formatMetricValue(metricId, currentVal)}${change}`,
    );
  }

  lines.push("", "Notes", "────────────────");
  lines.push(
    "This document was created from synthetic demo analytics in Commerce Intelligence.",
  );
  lines.push("Review figures against your live commerce sources before sharing.");

  return lines.join("\n");
}

function formatMetricValue(metricId: MetricId, value: number): string {
  if (
    metricId === "roas" ||
    metricId === "conversion_rate" ||
    metricId.includes("rate")
  ) {
    return value.toFixed(2);
  }
  if (metricId === "revenue" || metricId === "ad_spend") {
    return `₹${Math.round(value).toLocaleString("en-IN")}`;
  }
  return Math.round(value).toLocaleString("en-IN");
}
